#!/bin/sh

sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9

bspc config border_width         0
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Zathura state=tiled
bspc rule -a Nightly state=tiled
bspc rule -a discord desktop=6

